spring:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: